from . import res_partner_customer
from . import res_partner_member
from . import product_category
from . import product_services
from . import product_packages
from . import card_type
from . import member_vehicle_type
from . import member_vehicle_model
from . import location
from . import external_service
from . import member_search
from . import data_upload_file
from . import member_upload_cancel
from . import credit_member_upload
from . import aaa_service