# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development
- qa
- uat
- gama
- kirkosalpha
resources:
- repo: self

variables:

  - group: Development

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
      # name: alpha
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(aaaerpimageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(ACR_CONN)
        tags: |
          $(tag)
    # - task: SSH@0
    #   inputs:
    #     condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'alpha'))
    #     sshEndpoint: 'carhire-alpha'
    #     runOptions: 'commands'
    #     failOnStdErr: false
    #     commands: '/startscripts/aaa-odoo.sh'
    #     readyTimeout: '20000'

    - task: SSH@0
      inputs:
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'kirkosalpha'))
        sshEndpoint: 'kirkos-dev'
        runOptions: 'commands'
        failOnStdErr: false
        commands: '/startscripts/aaa-odoo.sh'
        readyTimeout: '20000' 
    
    - task: SSH@0
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'qa'))
      inputs:
        sshEndpoint: 'carhire-uat'
        failOnStdErr: false
        runOptions: 'commands'
        commands: '/startscripts/aaa-odoo-qa.sh'
        readyTimeout: '20000'

    - task: SSH@0
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'uat'))
      inputs:
        sshEndpoint: 'carhire-uat'
        failOnStdErr: false
        runOptions: 'commands'
        commands: '/startscripts/aaa-odoo.sh'
        readyTimeout: '20000'
