# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development
- beta
- gama
resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '3cebb094-f6b4-4009-bfb1-9e05bca63dc3'
  imageRepository: 'aaaerp'
  containerRegistry: 'carhiredev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildSourceBranch)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: SSH@0
      inputs:
        sshEndpoint: 'carhire-alpha'
        runOptions: 'commands'
        failOnStdErr: false
        commands: '/startscripts/aaa-odoo.sh'
        readyTimeout: '20000'
