# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development
- qa
- UAT
- gama

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '6bda621f-ec6b-497b-b30e-8f2511dfdeaa'
  imageRepository: 'aaaerp'
  containerRegistry: 'carhiredev.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.SourceBranchName)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      # vmImage: $(vmImageName)
      name: alpha
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: SSH@0
      inputs:
        condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'alpha'))
        sshEndpoint: 'carhire-alpha'
        runOptions: 'commands'
        failOnStdErr: false
        commands: '/startscripts/aaa-odoo.sh'
        readyTimeout: '20000'
    
    - task: SSH@0
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'qa'))
      inputs:
        sshEndpoint: 'carhire-uat'
        failOnStdErr: false
        runOptions: 'commands'
        commands: '/startscripts/aaa-odoo-qa.sh'
        readyTimeout: '20000'

    - task: SSH@0
      condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'uat'))
      inputs:
        sshEndpoint: 'carhire-uat'
        failOnStdErr: false
        runOptions: 'commands'
        commands: '/startscripts/aaa-odoo.sh'
        readyTimeout: '20000'
