[options]
db_host = 10.1.0.8
db_name = AAA-odoo
db_user = odoo
db_password = carhire
db_port = 5433
addons_path = /opt/odoo/addons,/opt/odoo/custom
admin_passwd = admin
pg_path = 
http_port = 8070
without_demo = true
static_url_prefix = /opt/odoo/addons/web/static/
log_level = debug
logfile = /var/log/odoo/odoo.log