[options]
db_host = localhost
db_name = AAA
db_user = odoo13
db_password = odoo13
db_port = 5432
addons_path = C:\Users\Jishad\Documents\ODOO\odoo-17.0\addons,C:\Users\Jishad\Documents\ODOO\odoo-17.0\custom
admin_passwd = $pbkdf2-sha512$600000$.J9TyjnnnLO2FkKolZKS0g$2DIkwcxPD4xzoX/OsgQy.Jr5x7wPy1a4ApBFa0aiki8Y3HmT1G.Ne6C7989quFcboSkjZmBNjsBmoDsTRmHnBA
pg_path = C:\Program Files\PostgreSQL\9.5\bin
bin_path = C:\Program Files\wkhtmltopdf\bin
http_port = 8070
without_demo = true

