[options]
db_host = localhost
db_name = False
db_user = odoo13
db_password = odoo13
db_port = 5432
addons_path = C:\Users\Jishad\Documents\ODOO\odoo-17.0\addons,C:\Users\Jishad\Documents\ODOO\odoo-17.0\custom
admin_passwd = $pbkdf2-sha512$600000$Q.i9VwphjHEuhZBy7j2n9A$83LSv4Ie1IbvsiXUf5qnS1iNzi3vWbuVKBZ6KUYQjFPs6eon/CIwXaebtLzifM8632Q5FmM57RvsZ7lwwPmL7g
pg_path = C:\Program Files\PostgreSQL\9.5\bin
bin_path = C:\Program Files\wkhtmltopdf\bin
http_port = 8070

