# customer/__manifest__.py
{
    'name': 'Customer',
    'version': '1.0',
    'depends': ['base', 'web','product'],
    'author': 'Sasoft',
    'category': 'Sales',
    'description': 'Customers Management',
    'data': [
        'security/ir.model.access.csv',
        'views/res_partner_customer.xml',
        'views/res_partner_member.xml',
        'views/res_partner_member_temp.xml',
        'views/res_partner_member_cancel.xml',
        'views/config_product.xml',
        'views/card_type.xml',
        'views/country_code.xml',
        'views/product_packages.xml',
        'views/product_category.xml',
        'views/member_vehicle_type.xml',
        'views/member_vehicle_model.xml',
        'views/location.xml',
        'views/external_service.xml',
        'views/res_partner_adhoc_member.xml',
        'views/res_partner_credit_member.xml',
        'views/product_service.xml',
        'views/policy_member_search.xml',
        'views/credit_member_search.xml',
        'views/data_upload_file.xml',
        'views/upload_history.xml',
        'views/member_upload_cancel.xml',
        'views/rejected_upload_members.xml',
        'views/cancellation_history.xml',
        'views/credit_member_upload.xml',
        'views/credit_member_upload_history.xml',
        'views/credit_member_upload_rejected.xml',
        'views/call_center_menu.xml',
        'views/call_center_service_form.xml',
        'views/call_center_enquiry.xml',
        'views/call_center_all_service_view.xml',
        'views/policy_member_service_history.xml',
        'views/res_partner_vendor.xml',
        'wizards/upload_member_wizard.xml',
        'wizards/membership_extension_wizard.xml',
        'wizards/membership_renewal_wizard.xml',
        'wizards/membership_cancel_wizard.xml',
        'wizards/member_cancel_upload_wizard.xml',
        'wizards/credit_member_upload_wizard.xml',
        'wizards/service_dispatch_wizard.xml',
        'wizards/service_cash_wizard.xml',
        'wizards/schedule_service_wizard.xml',
        'data/scheduled_action.xml',
        'data/sequence_data.xml',
        # 'views/product_packages.xml',
        # 'static/src/js/customer.js',
    ],
    'installable': True,
    'application': True,
    'sequence': 2,
}
