# customer/__manifest__.py
{
    'name': 'Customer',
    'version': '1.0',
    'depends': ['web','base','product','hr','mail','account','report_xlsx','bus'],
    'assets': {
        'web.assets_backend': [
             '/customer/static/src/css/my_custom_style.css',
             '/customer/static/src/css/aaa_service.css',
             '/customer/static/src/css/custom_menu.css',
            #  '/customer/static/src/css/location_field.css',
            #  '/customer/static/src/js/location_field.js',
            #  '/customer/static/src/xml/location_field.xml',
            '/customer/static/src/js/realtime_updates.js',
        ],
        'web.report_assets_common': [
            # '/customer/static/src/css/fonts.css',
        ],
    },
    'author': 'Sasoft',
    'category': 'Customer',
    'description': 'Customers Management',
    'data': [
        'security/ir.model.access.csv',
        'reports/credit_validation_pdf_report.xml',
        'reports/credit_invoice_pdf_report.xml',
        'reports/reports.xml',
        'views/res_partner_customer.xml',
        'views/res_partner_member.xml',
        'views/res_partner_membership_history.xml',
        'views/res_partner_member_renewal_queue.xml',
        'views/res_partner_member_temp.xml',
        'views/res_partner_member_cancel.xml',
        'views/config_product.xml',
        'views/card_type.xml',
        'views/country_code.xml',
        'views/product_packages.xml',
        'views/product_category.xml',
        'views/member_vehicle_type.xml',
        'views/member_vehicle_model.xml',
        'views/location.xml',
        'views/external_service.xml',
        'views/res_partner_adhoc_member.xml',
        'views/res_partner_credit_member.xml',
        'views/product_service.xml',
        'views/policy_member_search.xml',
        'views/credit_member_search.xml',
        'views/data_upload_file.xml',
        'views/upload_history.xml',
        'views/member_upload_cancel.xml',
        'views/rejected_upload_members.xml',
        'views/cancellation_history.xml',
        'views/credit_member_upload.xml',
        'views/credit_member_upload_history.xml',
        'views/credit_member_upload_rejected.xml',
        'views/call_center_menu.xml',
        'views/call_center_service_form.xml',
        'views/call_center_enquiry.xml',
        'views/call_center_all_service_view.xml',
        'views/credit_service_validation.xml',
        'views/policy_member_service_history.xml',
        'views/res_partner_vendor.xml',
        'views/product_pricelist.xml',
        'views/service_dashboard.xml',
        'views/afl_service.xml',
        'views/accounts_addons.xml',
        'views/invoice_addons.xml',
        # 'views/res_partner_action.xml',
        'views/afl_dashboard.xml',
        'wizards/upload_member_wizard.xml',
        'wizards/membership_extension_wizard.xml',
        'wizards/membership_renewal_wizard.xml',
        'wizards/membership_cancel_wizard.xml',
        'wizards/member_cancel_upload_wizard.xml',
        'wizards/credit_member_upload_wizard.xml',
        'wizards/service_dispatch_wizard.xml',
        'wizards/service_cash_wizard.xml',
        'wizards/schedule_service_wizard.xml',
        'wizards/service_report_wizard_view.xml',
        'wizards/enquiry_complaint_wizard.xml',
        'wizards/create_temporary_member_wizard.xml',
        'wizards/aaa_report_wizard.xml',
        'wizards/aaa_timeline_wizard.xml',
        'wizards/policy_report_wizard_view.xml',
        'wizards/vendors_report_wizard.xml',
        'wizards/aaa_rac_wizard.xml',
        'wizards/rac_bulk_upload.xml',
        'wizards/aaa_cancel_report.xml',
        'data/scheduled_action.xml',
        'data/sequence_data.xml',
        'data/server_action.xml',
    ],
    'installable': True,
    'application': True,
    'sequence': 2,
}
