from . import upload_member_wizard
from . import membership_extension_wizard
from . import membership_renewal_wizard
from . import membership_cancel_wizard
from . import member_cancel_upload_wizard
from . import credit_member_upload_wizard
from . import service_dispatch_wizard
from . import service_cash_wizard
from . import schedule_service_wizard
from . import service_report_wizard_view
from . import enquiry_complaint_wizard
from . import create_temporary_member_wizard